FROM rasa/rasa-sdk:3.6.2

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r /app/requirements.txt || true

EXPOSE 5055

# Start the Rasa Action Server
CMD ["python", "-m", "rasa_sdk", "--actions", "actions", "--port", "5055"]