FROM rasa/rasa-sdk:3.6.2

WORKDIR /app
COPY actions.py .
COPY requirements.txt .

USER root
RUN pip install --no-cache-dir -r requirements.txt
USER 1001

EXPOSE 5055
CMD ["start", "--actions", "actions"]